import type { Player, Tournament, Match, News, Achievement, Sponsor } from "./types"

export const dummyPlayers: Player[] = [
  {
    id: "1",
    name: "Shadow Strike",
    position: "Forward",
    avatar: "/gamer-avatar-1.png",
    played: 18,
    won: 14,
    drawn: 2,
    lost: 2,
    goalsFor: 42,
    goalsAgainst: 15,
    goalDifference: 27,
    points: 44,
    form: ["W", "W", "W", "D", "W"],
    status: "full",
  },
  {
    id: "2",
    name: "Phantom Ace",
    position: "Midfielder",
    avatar: "/gamer-avatar-2.png",
    played: 18,
    won: 13,
    drawn: 3,
    lost: 2,
    goalsFor: 38,
    goalsAgainst: 18,
    goalDifference: 20,
    points: 42,
    form: ["W", "D", "W", "W", "W"],
    status: "full",
  },
  {
    id: "3",
    name: "Viper Elite",
    position: "Defender",
    avatar: "/gamer-avatar-3.png",
    played: 18,
    won: 12,
    drawn: 4,
    lost: 2,
    goalsFor: 35,
    goalsAgainst: 16,
    goalDifference: 19,
    points: 40,
    form: ["W", "W", "D", "W", "L"],
    status: "full",
  },
  {
    id: "4",
    name: "Blaze Runner",
    position: "Forward",
    avatar: "/gamer-avatar-4.png",
    played: 18,
    won: 11,
    drawn: 5,
    lost: 2,
    goalsFor: 33,
    goalsAgainst: 19,
    goalDifference: 14,
    points: 38,
    form: ["D", "W", "W", "D", "W"],
    status: "full",
  },
  {
    id: "5",
    name: "Frost Byte",
    position: "Goalkeeper",
    avatar: "/gamer-avatar-5.png",
    played: 18,
    won: 11,
    drawn: 4,
    lost: 3,
    goalsFor: 30,
    goalsAgainst: 20,
    goalDifference: 10,
    points: 37,
    form: ["W", "L", "W", "W", "D"],
    status: "full",
  },
  {
    id: "6",
    name: "Thunder Bolt",
    position: "Midfielder",
    avatar: "/gamer-avatar-6.png",
    played: 18,
    won: 10,
    drawn: 5,
    lost: 3,
    goalsFor: 32,
    goalsAgainst: 22,
    goalDifference: 10,
    points: 35,
    form: ["D", "W", "L", "W", "W"],
    status: "full",
  },
  {
    id: "7",
    name: "Crimson Hawk",
    position: "Forward",
    avatar: "/gamer-avatar-7.jpg",
    played: 18,
    won: 10,
    drawn: 4,
    lost: 4,
    goalsFor: 31,
    goalsAgainst: 23,
    goalDifference: 8,
    points: 34,
    form: ["W", "W", "L", "D", "W"],
    status: "full",
  },
  {
    id: "8",
    name: "Steel Titan",
    position: "Defender",
    avatar: "/gamer-avatar-8.jpg",
    played: 18,
    won: 9,
    drawn: 6,
    lost: 3,
    goalsFor: 28,
    goalsAgainst: 21,
    goalDifference: 7,
    points: 33,
    form: ["D", "D", "W", "W", "L"],
    status: "full",
  },
  {
    id: "9",
    name: "Nova Storm",
    position: "Midfielder",
    avatar: "/gamer-avatar-9.jpg",
    played: 18,
    won: 9,
    drawn: 5,
    lost: 4,
    goalsFor: 29,
    goalsAgainst: 24,
    goalDifference: 5,
    points: 32,
    form: ["W", "L", "D", "W", "W"],
    status: "full",
  },
  {
    id: "10",
    name: "Rogue Sniper",
    position: "Forward",
    avatar: "/gamer-avatar-10.jpg",
    played: 18,
    won: 9,
    drawn: 4,
    lost: 5,
    goalsFor: 27,
    goalsAgainst: 25,
    goalDifference: 2,
    points: 31,
    form: ["L", "W", "W", "D", "L"],
    status: "full",
  },
  {
    id: "11",
    name: "Apex Predator",
    position: "Defender",
    avatar: "/gamer-avatar-11.jpg",
    played: 18,
    won: 8,
    drawn: 6,
    lost: 4,
    goalsFor: 26,
    goalsAgainst: 24,
    goalDifference: 2,
    points: 30,
    form: ["D", "W", "L", "D", "W"],
    status: "full",
  },
  {
    id: "12",
    name: "Cyber Ghost",
    position: "Midfielder",
    avatar: "/gamer-avatar-12.jpg",
    played: 18,
    won: 8,
    drawn: 5,
    lost: 5,
    goalsFor: 25,
    goalsAgainst: 26,
    goalDifference: -1,
    points: 29,
    form: ["L", "D", "W", "W", "L"],
    status: "full",
  },
  {
    id: "13",
    name: "Omega Force",
    position: "Forward",
    avatar: "/gamer-avatar-13.jpg",
    played: 18,
    won: 7,
    drawn: 7,
    lost: 4,
    goalsFor: 24,
    goalsAgainst: 25,
    goalDifference: -1,
    points: 28,
    form: ["D", "D", "W", "L", "D"],
    status: "full",
  },
  {
    id: "14",
    name: "Neon Blade",
    position: "Midfielder",
    avatar: "/gamer-avatar-14.jpg",
    played: 18,
    won: 7,
    drawn: 6,
    lost: 5,
    goalsFor: 23,
    goalsAgainst: 27,
    goalDifference: -4,
    points: 27,
    form: ["L", "W", "D", "L", "W"],
    status: "full",
  },
  {
    id: "15",
    name: "Dark Phoenix",
    position: "Defender",
    avatar: "/gamer-avatar-15.jpg",
    played: 18,
    won: 6,
    drawn: 8,
    lost: 4,
    goalsFor: 22,
    goalsAgainst: 26,
    goalDifference: -4,
    points: 26,
    form: ["D", "D", "L", "D", "W"],
    status: "full",
  },
  {
    id: "16",
    name: "Quantum Shift",
    position: "Forward",
    avatar: "/gamer-avatar-16.jpg",
    played: 18,
    won: 6,
    drawn: 7,
    lost: 5,
    goalsFor: 21,
    goalsAgainst: 28,
    goalDifference: -7,
    points: 25,
    form: ["L", "D", "W", "D", "L"],
    status: "full",
  },
  {
    id: "17",
    name: "Inferno King",
    position: "Midfielder",
    avatar: "/gamer-avatar-17.jpg",
    played: 18,
    won: 5,
    drawn: 8,
    lost: 5,
    goalsFor: 20,
    goalsAgainst: 28,
    goalDifference: -8,
    points: 23,
    form: ["D", "L", "D", "W", "D"],
    status: "full",
  },
  {
    id: "18",
    name: "Eclipse Warrior",
    position: "Defender",
    avatar: "/gamer-avatar-18.jpg",
    played: 18,
    won: 5,
    drawn: 6,
    lost: 7,
    goalsFor: 19,
    goalsAgainst: 30,
    goalDifference: -11,
    points: 21,
    form: ["L", "L", "D", "W", "L"],
    status: "full",
  },
  {
    id: "19",
    name: "Volt Striker",
    position: "Forward",
    avatar: "/gamer-avatar-19.jpg",
    played: 18,
    won: 4,
    drawn: 7,
    lost: 7,
    goalsFor: 18,
    goalsAgainst: 31,
    goalDifference: -13,
    points: 19,
    form: ["L", "D", "L", "D", "W"],
    status: "full",
  },
  {
    id: "20",
    name: "Chaos Reaper",
    position: "Midfielder",
    avatar: "/gamer-avatar-20.jpg",
    played: 18,
    won: 3,
    drawn: 8,
    lost: 7,
    goalsFor: 17,
    goalsAgainst: 32,
    goalDifference: -15,
    points: 17,
    form: ["D", "L", "L", "D", "L"],
    status: "full",
  },
]

export const dummyTournaments: Tournament[] = [
  {
    id: "1",
    name: "BOE Championship 2025",
    type: "league",
    season: "2025",
    status: "ongoing",
    startDate: "2025-01-15",
    image: "/esports-tournament-championship.jpg",
  },
  {
    id: "2",
    name: "Elite Cup",
    type: "cup",
    season: "2025",
    status: "upcoming",
    startDate: "2025-03-01",
    image: "/gaming-cup-tournament.jpg",
  },
  {
    id: "3",
    name: "Solo Masters",
    type: "solo",
    season: "2025",
    status: "ongoing",
    startDate: "2025-02-01",
    image: "/solo-gaming-competition.jpg",
  },
  {
    id: "4",
    name: "Winter Invitational",
    type: "league",
    season: "2024-2025",
    status: "completed",
    startDate: "2024-12-01",
    endDate: "2025-01-10",
    image: "/winter-esports-event.jpg",
  },
  {
    id: "5",
    name: "Brotherhood Clash",
    type: "cup",
    season: "2025",
    status: "upcoming",
    startDate: "2025-04-15",
    image: "/gaming-clash-tournament.jpg",
  },
]

export const dummyMatches: Match[] = [
  {
    id: "1",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Shadow Strike",
    awayPlayer: "Phantom Ace",
    homeScore: null,
    awayScore: null,
    date: "2025-01-25T18:00:00",
    venue: "Arena Alpha",
    status: "scheduled",
    matchType: "player-vs-player",
  },
  {
    id: "2",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Viper Elite",
    awayPlayer: "Blaze Runner",
    homeScore: null,
    awayScore: null,
    date: "2025-01-26T19:00:00",
    venue: "Arena Beta",
    status: "scheduled",
    matchType: "player-vs-player",
  },
  {
    id: "3",
    tournamentId: "3",
    tournamentName: "Solo Masters",
    homePlayer: "Frost Byte",
    awayPlayer: "Thunder Bolt",
    homeScore: null,
    awayScore: null,
    date: "2025-01-27T20:00:00",
    venue: "Digital Dome",
    status: "scheduled",
    matchType: "intra-club",
  },
  {
    id: "4",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Crimson Hawk",
    awayPlayer: "Steel Titan",
    homeScore: 2,
    awayScore: 1,
    date: "2025-01-20T18:00:00",
    venue: "Arena Alpha",
    status: "live",
    matchType: "player-vs-player",
  },
  {
    id: "5",
    tournamentId: "3",
    tournamentName: "Solo Masters",
    homePlayer: "Nova Storm",
    awayPlayer: "Rogue Sniper",
    homeScore: 1,
    awayScore: 1,
    date: "2025-01-20T19:30:00",
    venue: "Cyber Stadium",
    status: "live",
    matchType: "intra-club",
  },
  {
    id: "6",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Shadow Strike",
    awayPlayer: "Viper Elite",
    homeScore: 3,
    awayScore: 2,
    date: "2025-01-18T18:00:00",
    venue: "Arena Alpha",
    status: "completed",
    matchType: "player-vs-player",
  },
  {
    id: "7",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Phantom Ace",
    awayPlayer: "Blaze Runner",
    homeScore: 2,
    awayScore: 2,
    date: "2025-01-17T19:00:00",
    venue: "Arena Beta",
    status: "completed",
    matchType: "player-vs-player",
  },
  {
    id: "8",
    tournamentId: "3",
    tournamentName: "Solo Masters",
    homePlayer: "Frost Byte",
    awayPlayer: "Crimson Hawk",
    homeScore: 1,
    awayScore: 3,
    date: "2025-01-16T20:00:00",
    venue: "Digital Dome",
    status: "completed",
    matchType: "intra-club",
  },
  {
    id: "9",
    tournamentId: "1",
    tournamentName: "BOE Championship 2025",
    homePlayer: "Thunder Bolt",
    awayPlayer: "Steel Titan",
    homeScore: 2,
    awayScore: 0,
    date: "2025-01-15T18:00:00",
    venue: "Arena Alpha",
    status: "completed",
    matchType: "player-vs-player",
  },
  {
    id: "10",
    tournamentId: "3",
    tournamentName: "Solo Masters",
    homePlayer: "Nova Storm",
    awayPlayer: "Apex Predator",
    homeScore: 4,
    awayScore: 1,
    date: "2025-01-14T19:00:00",
    venue: "Cyber Stadium",
    status: "completed",
    matchType: "intra-club",
  },
]

export const dummyNews: News[] = [
  {
    id: "1",
    title: "BOE Dominates Regional Championship",
    date: "2025-01-15",
    excerpt: "Brotherhood of Excellence secures first place in the regional finals with an outstanding performance.",
    content:
      "In an electrifying display of skill and teamwork, the Brotherhood of Excellence gaming club has claimed victory in the regional championship. Shadow Strike led the charge with exceptional gameplay, supported by the entire roster.",
    image: "/esports-championship-victory.jpg",
  },
  {
    id: "2",
    title: "New Training Facility Opens",
    date: "2025-01-10",
    excerpt: "State-of-the-art gaming facility now available for all BOE members.",
    content:
      "BOE is proud to announce the opening of our new training facility, equipped with the latest gaming hardware and coaching resources. This facility will help our players reach new heights in competitive gaming.",
    image: "/gaming-training-facility.jpg",
  },
  {
    id: "3",
    title: "Phantom Ace Reaches 1000 Wins",
    date: "2025-01-05",
    excerpt: "Club legend achieves historic milestone in competitive play.",
    content:
      "Phantom Ace has become the first BOE player to reach 1000 competitive wins, cementing their legacy as one of the greatest players in club history. The achievement was celebrated by the entire gaming community.",
    image: "/esports-player-milestone.jpg",
  },
  {
    id: "4",
    title: "BOE Announces Partnership with Elite Gaming",
    date: "2024-12-28",
    excerpt: "Strategic partnership brings new opportunities for club members.",
    content:
      "We are excited to announce our partnership with Elite Gaming, a leading esports organization. This collaboration will provide our players with access to professional coaching, tournaments, and career development opportunities.",
    image: "/esports-partnership-announcement.jpg",
  },
  {
    id: "5",
    title: "Upcoming Tournament Schedule Released",
    date: "2024-12-20",
    excerpt: "Mark your calendars for an action-packed 2025 season.",
    content:
      "The 2025 tournament schedule is here! BOE will be competing in multiple leagues and cups throughout the year. Check out the full schedule on our tournaments page and get ready for an incredible season.",
    image: "/gaming-tournament-schedule.jpg",
  },
]

export const dummyAchievements: Achievement[] = [
  {
    id: "1",
    title: "Regional Champions 2024",
    year: "2024",
    description: "First place in the Regional Championship",
    image: "/gold-trophy-championship.jpg",
  },
  {
    id: "2",
    title: "National Tournament Runners-Up",
    year: "2024",
    description: "Second place in National Finals",
    image: "/silver-trophy-medal.jpg",
  },
  {
    id: "3",
    title: "Best Team Spirit Award",
    year: "2023",
    description: "Recognized for exceptional teamwork",
    image: "/team-spirit-award.jpg",
  },
  {
    id: "4",
    title: "League Champions 2023",
    year: "2023",
    description: "Undefeated season champions",
    image: "/championship-belt-trophy.jpg",
  },
  {
    id: "5",
    title: "Community Excellence Award",
    year: "2023",
    description: "Outstanding community engagement",
    image: "/community-excellence-badge.jpg",
  },
]

export const dummySponsors: Sponsor[] = [
  {
    id: "1",
    name: "Elite Gaming Gear",
    logo: "/gaming-gear-logo.jpg",
    website: "https://example.com",
  },
  {
    id: "2",
    name: "ProStream Network",
    logo: "/placeholder.svg?height=100&width=200",
    website: "https://example.com",
  },
  {
    id: "3",
    name: "Energy Boost Drinks",
    logo: "/placeholder.svg?height=100&width=200",
    website: "https://example.com",
  },
]
